name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    # Cache APT Packages
    - name: Cache APT Packages
      uses: awalsh128/cache-apt-pkgs-action@v1.3.1
      with:
        key: ${{ runner.os }}-apt-cache-${{ hashFiles('.github/workflows/apt-packages.txt') }}

    # Install dependencies
    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y make gcc g++ libasio-dev nlohmann-json3-dev
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: Clone Lib Commune
      run: git clone https://github.com/robotronik/librairie-commune.git ../librairie-commune

    - name: make tests
      run: make tests

    - name: make
      run: make
