name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    # Install dependencies
    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y make gcc g++ libasio-dev nlohmann-json3-dev
    
    - name: Clone Lib Commune
      run: git clone https://github.com/robotronik/librairie-commune.git ../librairie-commune

    - name: Clone Aruco OpenCV
      run: git clone https://github.com/robotronik/PythonArucoOpenCV.git ../PythonArucoOpenCV
          
    - name: make tests
      run: make tests
    - name: make
      run: make
    
    - name: Cache APT Packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt/archives
        key: ${{ runner.os }}-apt-cache
